# Generated by Django 5.1 on 2024-08-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
