# Generated by Django 5.1 on 2024-08-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0002_alter_recipe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
