# Generated by Django 5.1 on 2024-08-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0009_alter_reportcard_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='date_of_reportcard_generation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
