# Generated by Django 5.1 on 2024-08-23 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0010_alter_reportcard_date_of_reportcard_generation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank',)},
        ),
    ]
