# Generated by Django 5.1 on 2024-08-23 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0011_alter_reportcard_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together=set(),
        ),
    ]
