# Generated by Django 5.1 on 2024-08-23 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0012_alter_reportcard_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_reportcard_generation')},
        ),
    ]
