# Generated by Django 5.1 on 2024-08-23 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0013_alter_reportcard_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 8, 23, 11, 0, 9, 417823, tzinfo=datetime.timezone.utc), unique=True),
            preserve_default=False,
        ),
    ]
